### ISSUE TITLE
chef-rundeck doesn't working - check_version_conflict

### ISSUE THREAD

**Issue by yorchtf** [Webtrends/rundeck#100]
When I execute the command in my ktichen machine:

`# /opt/chef/embedded/bin/ruby /opt/chef/embedded/bin/chef-rundeck -c /etc/chef/rundeck.rb -f /etc/chef/chef-rundeck.json -w https://chefserver.system73.com/organizations/system73 -o 0.0.0.0 -p 9980 -t 10`

**/opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2278:in `check_version_conflict': can't activate rack-2.0.1, already activated rack-1.6.4 (Gem::LoadError)**
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1404:in `activate'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:239:in`block in finish_resolve'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:238:in `each'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:238:in`finish_resolve'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/rdoc.rb:15:in `<top (required)>'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in`require'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/uninstaller.rb:11:in`<top (required)>'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in`require'
    from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider/package/rubygems.rb:37:in `<top (required)>'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in`require'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/providers.rb:80:in`<top (required)>'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in`require'
    from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef.rb:25:in `<top (required)>'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in`require'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-rundeck-2.2.0/lib/chef-rundeck.rb:18:in`<top (required)>'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in`require'
    from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-rundeck-2.2.0/bin/chef-rundeck:21:in `<top (required)>'
    from /opt/chef/embedded/bin/chef-rundeck:22:in`load'
    from /opt/chef/embedded/bin/chef-rundeck:22:in `<main>'

I can see the gems in the machine:

```
ls **/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/**
addressable-2.4.0        erubis-2.7.0                 multi_json-1.12.1           rack-1.6.4
appbundler-0.9.0         ffi-1.9.14                   net-scp-1.2.1               rack-2.0.1
....
```

**Comment by yorchtf** [comment]
solved   
https://github.com/sinatra/sinatra/issues/1055
